In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [17]:
# Load the Dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [18]:
## Preprocess the data
# Drop irrelevant columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
# Encode categorical varaibles
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])# One Hot encoding : "Geography"
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [19]:
import numpy as np
geo_column  = np.array(onehot_encoder_geo.get_feature_names_out())

In [20]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=geo_column)

In [21]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [22]:
# Combine OHE with original data
data = pd.concat([data.drop('Geography',axis=1), geo_encoded_df],axis=1)

In [23]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [24]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [25]:
## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# First, train-test split then STANDARDIZATION is done in order to PREVENT DATA-LEAKAGE COMPLETELY.

In [26]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [27]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

# ANN Regression Problem Statement

In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\Omkar Raut\Desktop\DataSceince\DL-venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [31]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape = (X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression where linear activation function is used by-default.
])

# Compile the Model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

In [32]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [33]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [ ]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [35]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Omkar Raut\Desktop\DataSceince\DL-venv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Omkar Raut\Desktop\DataSceince\DL-venv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 5ms/step - loss: 100386.2344 - mae: 100386.2344 - val_loss: 98552.3359 - val_mae: 98552.3359
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 99778.0000 - mae: 99778.0000 - val_loss: 97316.8438 - val_mae: 97316.8438
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 97651.8203 - mae: 97651.8203 - val_loss: 94175.8750 - val_mae: 94175.8750
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 93410.8750 - mae: 93410.8750 - val_loss: 88781.2266 - val_mae: 88781.2266
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 87033.1094 - mae: 87033.1094 - val_loss: 81570.7266 - val_mae: 81570.7266
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 79113.0547 - mae: 79113.0547 - val_loss: 73487.6719 - val_mae: 73487.6719
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 70853.6875 - mae: 70853.6875 - val_loss: 65826.1016 - val_mae: 65826.1016
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 63406.9219 - mae: 63406.9219 - val_loss: 59529.6680 - val_mae: 59529.6680
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 57692.7422 - mae: 57692.7422 - val_loss: 55146.4844 - val_mae: 55146.4844
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 54040.6055 - mae: 54040.6055 - val_loss: 52628.9102 - val_mae: 52628.9102
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 52006.1211 - mae: 52006.1211 - val_loss: 51396.0898 - val_mae: 51396.0898
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50976.8398 - mae: 50976.8398 - val_loss: 50878.6406 - val_mae: 50878.6406
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50483.7930 - mae: 50483.7930 - val_loss: 50659.3594 - val_mae: 50659.3594
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 50262.6016 - mae: 50262.6016 - val_loss: 50574.5781 - val_mae: 50574.5781
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50151.2109 - mae: 50151.2109 - val_loss: 50530.9141 - val_mae: 50530.9141
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50079.0859 - mae: 50079.0859 - val_loss: 50481.2969 - val_mae: 50481.2969
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50026.2812 - mae: 50026.2812 - val_loss: 50459.7695 - val_mae: 50459.7695
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 49982.3945 - mae: 49982.3945 - val_loss: 50421.2266 - val_mae: 50421.2266
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 49947.2344 - mae: 49947.2344 - val_loss: 50392.6992 - val_mae: 50392.6992
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49916.0625 - mae: 49916.0625 - val_loss: 50367.2773 - val_mae: 50367.2773
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49889.8438 - mae: 49889.8438 - val_loss: 50344.8047 - val_mae: 50344.8047
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49861.8555 - mae: 49861.8555 - val_loss: 50338.2773 - val_mae: 50338.2773
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49842.0312 - mae: 49842.0312 - val_loss: 50330.1406 - val_mae: 50330.1406
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49817.0586 - mae: 49817.0586 - val_loss: 50317.4141 - val_mae: 50317.4141
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49799.0664 - mae: 49799.0664 - val_loss: 50310.9961 - val_mae: 50310.9961
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49776.3203 - mae: 49776.3203 - val_loss: 50310.5430 - val_mae: 50310.5430
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49758.7656 - mae: 49758.7656 - val_loss: 50291.3906 - val_mae: 50291.3906
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49741.1680 - mae: 49741.1680 - val_loss: 50290.6289 - val_mae: 50290.6289
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49723.7930 - mae: 49723.7930 - val_loss: 50287.1719 - val_mae: 50287.1719
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49708.0195 - mae: 49708.0195 - val_loss: 50287.9258 - val_mae: 50287.9258
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49692.0898 - mae: 49692.0898 - val_loss: 50278.7578 - val_mae: 50278.7578
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49679.6484 - mae: 49679.6484 - val_loss: 50271.9648 - val_mae: 50271.9648
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49664.2305 - mae: 49664.2305 - val_loss: 50271.0000 - val_mae: 50271.0000
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49653.7344 - mae: 49653.7344 - val_loss: 50275.7031 - val_mae: 50275.7031
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49640.5234 - mae: 49640.5234 - val_loss: 50275.8086 - val_mae: 50275.8086
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49629.9062 - mae: 49629.9062 - val_loss: 50278.6406 - val_mae: 50278.6406
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49618.3867 - mae: 49618.3867 - val_loss: 50276.9023 - val_mae: 50276.9023
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49605.0039 - mae: 49605.0039 - val_loss: 50274.0859 - val_mae: 50274.0859
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49596.2930 - mae: 49596.2930 - val_loss: 50275.7344 - val_mae: 50275.7344
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49584.8164 - mae: 49584.8164 - val_loss: 50274.6094 - val_mae: 50274.6094
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49575.4102 - mae: 49575.4102 - val_loss: 50276.9023 - val_mae: 50276.9023
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 49566.1562 - mae: 49566.1562 - val_loss: 50285.3320 - val_mae: 50285.3320
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49555.6094 - mae: 49555.6094 - val_loss: 50289.1289 - val_mae: 50289.1289

In [36]:
%load_ext tensorboard

In [38]:
%tensorboard --logdir regressionlogs/fit/

Reusing TensorBoard on port 6009 (pid 17652), started 0:02:02 ago. (Use '!kill 17652' to kill it.)

In [44]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test,y_test)

63/63 [==============================] - 0s 4ms/step - loss: 50271.0000 - mae: 50271.0000

In [45]:
test_loss, test_mae

(50271.0, 50271.0)

In [46]:
model.save('regression_model.h5')

c:\Users\Omkar Raut\Desktop\DataSceince\DL-venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(